STRONGSORT:
  ECC: True # activate camera motion compensation default: True
  MC_LAMBDA: 0.995 # matching with both appearance (1 - MC_LAMBDA) and motion cost
  EMA_ALPHA: 0.9 # updates  appearance  state in  an exponential moving average manner
  MAX_DIST: 0.4 # The matching threshold. Samples with larger distance are considered an invalid match default: 0.2
  MAX_IOU_DISTANCE: 0.6 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 350 # Maximum number of missed misses before a track is deleted default: 30
  N_INIT: 3 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 150 # Maximum size of the appearance descriptors gallery default: 100

