name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Initialising AWS credentials
      env:
        DATA: ${{ secrets.AWS_ENV }}
      run: $DATA >> ${{github.workspace}}/.env
    - name: Run CI tests
      run: |
        python src/main.py ${{github.workspace}}/data/short_new_1.mp4
        if [ ! -f ${{github.workspace}}/tmp/court_video_reenc.mp4 ]; then
          echo "model run failed: output does not exist"
          exit 1
        fi

